"""
This type stub file was generated by pyright.
"""

class CluError(Exception):
    """A custom core Clu exception"""

    def __init__(self, message=...) -> None: ...

class CluNotImplemented(CluError):
    """A custom exception for not yet implemented features."""

    def __init__(self, message=...) -> None: ...

class CommandError(CluError):
    """An error raised when a `Command` fails."""

    ...

class CommandParserError(CluError):
    """An error raised when parsing a command fails."""

    ...

class CluBaseWarning(Warning):
    """Base warning for Clu."""

    ...

class CluWarning(UserWarning, CluBaseWarning):
    """The primary warning class."""

    ...

class CluDeprecationWarning(CluBaseWarning):
    """A warning for deprecated features."""

    ...
